baseurl = "friendorfoe.stage.ccnmtl.columbia.edu"
languageCode = "en-us"
title = "Friend or Foe"
MetaDataFormat = "yaml"

[params]
baseurl = "friendorfoe.stage.ccnmtl.columbia.edu"
case_repo_baseurl = "http://ccnmtl.columbia.edu/projects/caseconsortium/casestudies/"


[taxonomies]
    article = "article"
    biography = "biography"

